### ISSUE TITLE
Custom compose overwrites compose file

### ISSUE THREAD

**Issue by moroland** [ironstar-io/tokaido#182]
**What happened**:

Enabled custom compose because I wanted to use the drush xdebug container.
But every time I run tok up or tok rebuild, the compose file still being reset by tokaido.

**What you expected to happen**:

Don't touch! :)

**How to reproduce it (as minimally and precisely as possible)**:

tok config-set tokaido customcompose true
make some changes in the composer file (e.g. change drush image to image: tokaido/admin71-heavy-xdebug:edge)
run tok rebuild twice

**Anything else we need to know?**:

**Environment**:
- Tokaido version (use `tok version`): v1.9.1
- Operating system and version: OSX 10.14.5

**Comment by otakumike** [comment]
Thanks for reporting and including reproduction steps Roland. I'll try to get this patched and out in the next week

**Comment by otakumike** [comment]
This is going to require a bit more work than I originally expected. I've marked it for inclusion in 1.10, as it's a bit too big for a patch. 

1.10 is likely to come out sometime in July, depending on what other features need to be added.

**Comment by otakumike** [comment]
Looks like this is going to require some pretty heavy refactoring in order to fix. 

The problem comes down to the fact that we have to generate the docker-compose file fresh in order to remove the banner image. We could look at some text manipulation to remove the banner without changing the rest of the file but that has it's own challenges. 

Ultimately we're looking at doing away with using docker-compose in Tokaido 2.0 early next year, so I can't see much value to be had in fixing this now, given that it's not a quick thing. 

Sorry @moroland. Thank you for opening the issue but I'm afraid we aren't going to fix this one now.
