### ISSUE TITLE
services.proxy.networks contains non-unique items error on `tok up`

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#37]
**What happened**:
Tried to create a new Tokaido project; however, on `tok up` I receive the following error:
![screen shot 2018-09-11 at 4 06 05 pm](https://user-images.githubusercontent.com/1292616/45341179-002ab980-b5dd-11e8-8ee3-2cffb75b53a9.png)

**What you expected to happen**:
`tok up` should successfully complete without errors.

**How to reproduce it (as minimally and precisely as possible)**:
Occurs when running `tok up` or `tok destroy` on a new or pre-existing Tokaido project.

**Anything else we need to know?**:

**Environment**:
- Tokaido version (use `tok version`): v1.1.1
- Drupal version: Drupal 8 and Drupal 7 projects
- Operating system and version: Mac OSX Sierra (v10.12.6)

**Additional context**
N/A

**Comment by otakumike** [comment]
Thanks @Benjen. I saw this yesterday myself. Looks like a regression in 1.1.1. We're going to fix and release as soon as we can. 

The bug is caused when you run `tok up` more than once on a project. 

In the mean time, a workaround is to edit `~/.tok/proxy/docker-compose.yml` and remove _all_ of the networks that are duplicated (eg, all three copies of `unsw_default` in your case before running `tok up` again.

**Comment by otakumike** [comment]
I should point out you have to remove those networks from both the `networks:`  tree in the base of the yaml and the `networks:` tree inside the `proxy:` service definition

**Comment by Benjen** [comment]
Thanks @otakumike, that work around did the trick.

**Comment by otakumike** [comment]
@Benjen thanks again for this report. We've released version 1.1.2 this morning which fixes the issue introduced last week in 1.1.1. 

You can download the binaries on the [releases](https://github.com/ironstar-io/tokaido/releases/tag/1.1.2) page, or just run `brew upgrade tokaido` on your Mac. 

Thanks again!
Mike
