### ISSUE TITLE
Copy Lando's pass-through command ability

### ISSUE THREAD

**Issue by garrettw** [ironstar-io/tokaido#48]
As a simple matter of convenience, it would be nice to be able to run a limited set of commands inside the container without needing to SSH in. Lando supports prefixing a few commands with `lando` (specifically `drush`) that make it quicker for me to do what I need.

Furthermore, if I'm not mistaken, Lando also allows the developer to create custom pass-through commands in its `.lando.yml` config file.

**Comment by otakumike** [comment]
Hi @garrettw, 

We actually have this already. You can run `tok exec` to run any command inside the ssh container. Note that these are run from the home directory, rather than the web root. 

For example: `tok exec "cd /tokaido/site/docroot && drush status"`

I'm going to leave this issue open as a request for us to move the initial directory. It should be /tokaido/site/docroot (or whatever your drupal root is) and that'll save you a step.

**Comment by garrettw** [comment]
Good idea. Lando would start you off in the web root as well.

**Comment by otakumike** [comment]
I've added this capability to the bash Docker SSH image now. Next time you run `tok up`, it'll download the newest version and then you'll be able to run `tok exec` with the context set to the Drupal root directory. Thanks for the suggestion! I'll go ahead and close this issue now.
