### ISSUE TITLE
Add easy db import/export

### ISSUE THREAD

**Issue by garrettw** [ironstar-io/tokaido#50]
While Drush does have the ability to import and export SQL, I generally prefer Lando's method which looks like `lando db-import db.sql`. It's probably faster than Drush although I'm not totally sure. It would be nice if Tokaido had commands to do this, partly because it's not Drupal-specific, ~~and especially due to databases being lost on container shutdown~~.

**Comment by otakumike** [comment]
Another nice idea - thanks! Will leave this one here to be picked up soon.

**Comment by garrettw** [comment]
Incidentally, `lando db-import` supports both .sql and .sql.gz files -- and `lando db-export db.sql` generates a file called `db.sql.gz`.

**Comment by otakumike** [comment]
Hey @GarrettW - this feature is finally coming in Tokaido 1.6 in the form of snapshots. Once released, you'll have the ability to: 

- create snapshots with `tok snapshot new` and you can optionally give them aliases
- list snapshots with `tok snapshot list`
- restore snapshots with `tok snapshot restore` and optionally an ID number from `list` - if you don't specify one, you'll get the list and can enter the snapshot id there
- delete on or all snapshots with `tok snapshot delete [id]`

Each time to you do a restore, Tokaido will also run a cache purge (drush cc/cr and varnish purge) for you. 

And finally, all the snapshots are found in `.tok/local/snapshots` so you can optionally put your own backups in there and restore them from `tok snapshot`

Ultimately with the snapshot functionality, rather than just import/export, we're trying to create a workflow that encourages devs to test database breaking changes so they can just restore with the latest snapshot `tok snapshot restore 0`

Obligatory screenshot of the new functionality in action: 
![image](https://user-images.githubusercontent.com/9390978/53678171-51f00900-3d0f-11e9-8e78-5161bb761ebe.png)

Thanks for your patience on this feature. 1.6 should be out in the coming week.

**Comment by otakumike** [comment]
Closing this issue now as this feature will be rolled out in the next week with 1.6

**Comment by garrettw** [comment]
That sounds great but that's only one of my use cases. The other is when I need to spin up a dev copy of a live site so I can make some changes to it -- I pull down a copy of the database and need to quickly load it into the dev environment. With Lando I do this immediately after spinning up the container.
And that's not to mention the rare occasions that I actually need to upload my dev database back to production.

**Comment by otakumike** [comment]
You can do that with the snapshot functionality. 

For pulling down a copy from a remote env and loading it locally: It'll recognise any .sql.gz or .sql file you place into `.tok/local/snapshots` and you can restore this. 

For uploading from local to remote, you can just take a snapshot (`tok snapshot new`) and copy the resulting file from `.tok/local/snapshots` up to your remote. 

Although the recommended way to sync between local and remote envs would be using drush aliases, if you can, as that makes things even simpler.

**Comment by garrettw** [comment]
Ah ok, good to know.
