### ISSUE TITLE
Include container for phpMyAdmin, maybe by default

### ISSUE THREAD

**Issue by garrettw** [ironstar-io/tokaido#51]
Sometimes I run into situations where I need to browse through the database to inspect it, and phpMyAdmin (PMA) is a great tool for this. Lando makes it pretty easy to add a PMA container to a project, and I would definitely want similar functionality here rather than having to figure out how to manually install it inside a container.

**Comment by otakumike** [comment]
Hi @garretw,

We actually already have something in place for this, but not yet well documented (we're working on a new website). We decided to implement Adminer instead of PHPMyAdmin. 

To enable this, you can simply run: 
`tok config-set services adminer enabled true && tok up`

After `tok up` finishes again, you can then run `tok open adminer` and your browser will open to the adminer port. 

The database connection details are then just:
- Server: mysql
- Username: tokaido
- Password: tokaido
- Database: tokaido

![1537268842_2107_18092018_302x195](https://user-images.githubusercontent.com/9390978/45683467-22957780-bb87-11e8-818d-a127df1f5706.png)

Personally I haven't used Adminer, but a few people on my team here suggested it was a better option than PMA. Do you agree? Let me know if you'd like to see an option for PMA, as well as Adminer.

**Comment by garrettw** [comment]
All I know is, most people are comfortable and familiar with PMA and thus would probably expect it to be at least an option. But personally I'm ok using whatever works.

What's the syntax for turning on Adminer using the config file?

**Comment by otakumike** [comment]
For adminer, the config is: 

```
services:
  adminer:
    enabled: true
```
