### ISSUE TITLE
Specify Drush version in config

### ISSUE THREAD

**Issue by garrettw** [ironstar-io/tokaido#53]
I deal with projects that are built on D7 as well as D8, and some of them run on servers with older Drush versions. Would it be possible to specify an arbitrary version of Drush to install in the config file?

**Comment by otakumike** [comment]
Unfortunately this is a hard one to implement, as it would require pre-building multiple versions of the ssh Docker image and then downloading the one which contained the drush version requested. That requires a lot of admin time that is difficult for us to find right now. 

However, the official recommendation for installing Drush in a project is to put it in the actual project, rather than a global install. We do install [drush launcher](https://github.com/drush-ops/drush-launcher) so that you can easily resolve your local Drush install. This is the recommended approach both from Drush and from us. 

Thanks for opening the feature request, but unfortunately, we can't implement this one for you.

**Comment by garrettw** [comment]
For D7, I think Lando does something that would be similar to downloading a docker image and then once it's running, download the configured version of Drush inside of it. For D8, Drush is brought in with composer so no issue there at all, but for D7 sites that don't use composer at all, we use a global Drush config with Lando. Haven't really tried any other way with D7 so I guess I'll have to see what's possible. Thanks though.
