### ISSUE TITLE
Include registry_rebuild in Drush container

### ISSUE THREAD

**Issue by moroland** [ironstar-io/tokaido#87]
Drush registry_rebuild is a powerful tool, sometimes it's necessary for fixing issues. Some Drupal-specific stacks contain it by default. Would be nice to have it in the Drush container.

to install: drush @none dl registry_rebuild
https://www.drupal.org/project/registry_rebuild

**Comment by otakumike** [comment]
Hey Roland!

We want to try and avoid falling into a pattern where we add components into Tokaido that can be otherwise solved by using Composer and installing them in the repo directly. Otherwise, we end up with progressively bigger containers that take longer and longer to download. 

Since registry_rebuild can be installed with Composer, please do it that way.
