### ISSUE TITLE
Line wrapping in SSH shell

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#9]
**What happened**:
Entering a multiline command in the SSH shell window results in overwriting of existing text.

**What you expected to happen**:
Long command should wrap to a clear new line, rather than overwriting itself.

**How to reproduce it (as minimally and precisely as possible)**:
* Start server using `tok up`.
* SSH into container `ssh mysite.tok`
* Whilst in the shell type a long test string (including spaces) which forces the text to wrap to a new line. 

**Anything else we need to know?**:

**Environment**:
- Tokaido version (use `tok version`): v0.0.12
- Drupal version: 7
- Operating system and version: darwin/amd64 (OSX Sierra v10.12.6)

**Additional context**
Have provided a screencast showing issue.
[tok-ssh-line-wrapper-issue.mp4.zip](https://github.com/ironstar-io/tokaido/files/2272892/tok-ssh-line-wrapper-issue.mp4.zip)

**Comment by otakumike** [comment]
Thanks for the report as always. I'll look at getting this fixed for the next release (Aug 20)

**Comment by otakumike** [comment]
Hi Ben,

I haven't been able to replicate this on Termite (Linux), or iTerm2 of the default Terminal app on MacOS. 

I did a bit of Googling though and suspect that _this_ might fix it for you: 

`PS1="${debian_chroot:+($debian_chroot)}️🚅 \\[\e[0;102m\]\\[\e[1mLOCAL\\[\e[33m\]\\[\e[m\] \\[\e[36m\]${PROJECT_NAME}\\[\e[m\] \\[\e[33m\]\t\\[\e[m\] \\[\e[34m\]\w\\[\e[m\] \\[\e[32m\]\$\\[\e[m\] "`

Can you SSH into the Tokaido environment and run that command to reset the PS1 environment variable (which gives Bash it's prompt). 

That might help? If not, maybe try using iTerm 2 instead of the native Terminal.app in macOS?

**Comment by Benjen** [comment]
Hi Mike,

I tried the reset command provided, but to no avail. Same issue was occurring.

I followed your advice and installed iTerm2 which appears to have resolved the issue.

**Comment by otakumike** [comment]
Thanks Ben. I'll close this card then since we don't have a path to debug and resolve. 

There are some really awesome features in iTerm tho, which are [worth checking out](https://www.iterm2.com/features.html)
