### ISSUE TITLE
Tokaido up command freezes

### ISSUE THREAD

**Issue by Benjen** [ironstar-io/tokaido#90]
**What happened**:
After running `tok up` the "tokaido is starting up" message is displayed after which nothing happens. After many minutes nothing has changed. Seems frozen.

**What you expected to happen**:
`tok up` should finish running as per normal.

**How to reproduce it (as minimally and precisely as possible)**:
* Ran `tok up` to start site on an existing tokaido project. By "existing" I mean that the project has been previously built locally using Tokaido and at that time the build resulted in a working website.
* Checked status of file syncing service using `tok status`. Noticed that file sync was not working which I believe is a known issue when using Tokaido on OSX.
* Ran `tok up` again to fix issue as per onscreen instructions: "... Tokaido will run, but your environment and local host will not be synchronised. Use 'tok up' to repair, or 'tok sync' to sync manually ..."
* At this point tokaido appears to freeze indefinitely after displaying the Tokaido is starting message.

**Anything else we need to know?**:

**Environment**:
- Tokaido version (use `tok version`): v1.4.1
- Drupal version: 8.6.3
- Operating system and version: OSX Sierra v10.12.6

**Additional context**

**Comment by otakumike** [comment]
Hey Ben! 

Thanks for the screen share with @yjimk and I. As we found, the 'hidden' unison sync process on a very large application gave the impression that Tokaido had stalled in some circumstances, but that there was another problem with Unison being reachable. Your reboot also seemed to somehow fix the issue. 

Here's what we decided we could do about this: 

- We'll add a stream of the Unison sync output when in debug mode
- We'll add a "Tokaido is syncing content" message when Unison is running, to make it clear that Unison _is_ running
- We'll add a feature toggle that lets users turn off Unison and just use the slower Docker virtual disk mounts on Mac. 

The first two of these features will be out really soon for the next release. The third is probably going to take us a while, and might ship in 1.5 or 1.6. 

I'll go ahead and close this ticket since we've mostly resolved your particular issue. Thanks again for taking the time to debug with us! 

Richo
